<#
.SYNOPSIS
    Master reporting script that orchestrates IT data collection and generates
    a consolidated HTML dashboard report.

.DESCRIPTION
    This script acts as the central orchestrator for the PowerShell Toolkit. It:
    - Invokes Get-ADUserReport.ps1 to capture Active Directory user data
    - Invokes Get-SystemInventory.ps1 for each target computer
    - Combines all collected data into a single polished HTML report
    - Includes summary tables, color-coded status indicators, and charts (CSS-based)
    - Optionally emails the report to IT management

    The HTML report is self-contained (inline CSS, no external dependencies) and
    can be viewed in any modern browser or emailed directly.

.PARAMETER ADReportPath
    Path to an existing AD user report CSV (generated by Get-ADUserReport.ps1).
    If omitted, AD section is skipped.

.PARAMETER InventoryPath
    Path to a directory containing JSON inventory files (from Get-SystemInventory.ps1).
    If omitted, inventory section is skipped.

.PARAMETER TargetComputers
    Array of computer names to run inventory against directly. Alternative to
    providing pre-generated inventory files.

.PARAMETER HtmlOutput
    Path where the final HTML report will be saved.

.PARAMETER CompanyName
    Company name to display in the report header.

.PARAMETER SendEmail
    Switch to enable emailing the report after generation.

.PARAMETER SmtpServer
    SMTP server for email delivery (requires -SendEmail).

.PARAMETER MailFrom
    From address for the email (requires -SendEmail).

.PARAMETER MailTo
    Recipient address(es) for the email (requires -SendEmail).

.PARAMETER Credential
    Credential for remote inventory if -TargetComputers is used.

.EXAMPLE
    .\Invoke-ITReport.ps1 -ADReportPath "C:\Reports\AD_Users.csv" -InventoryPath "C:\Reports\Inventory" -HtmlOutput "C:\Reports\Dashboard.html"

    Generate a dashboard from existing AD and inventory data.

.EXAMPLE
    .\Invoke-ITReport.ps1 -TargetComputers "SRV-APP-01","SRV-DB-01","PC-WKS-045" -HtmlOutput "C:\Reports\Dashboard.html" -CompanyName "Contoso Ltd."

    Run inventory against three machines and generate a dashboard.

.EXAMPLE
    .\Invoke-ITReport.ps1 -ADReportPath "C:\Reports\AD_Users.csv" -InventoryPath "C:\Reports\Inventory" -HtmlOutput "C:\Reports\Dashboard.html" -SendEmail -SmtpServer "smtp.contoso.com" -MailFrom "it@contoso.com" -MailTo "manager@contoso.com"

    Generate the report and email it to management.

.NOTES
    Author: Louis Denis RAZAFIMANDIMBY
    Requires: PowerShell 5.1+, output from Get-ADUserReport and Get-SystemInventory
    Version: 1.2
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [ValidateScript({ Test-Path $_ -PathType Leaf })]
    [string]$ADReportPath,

    [Parameter(Mandatory = $false)]
    [ValidateScript({ Test-Path $_ -PathType Container })]
    [string]$InventoryPath,

    [Parameter(Mandatory = $false)]
    [string[]]$TargetComputers,

    [Parameter(Mandatory = $true, HelpMessage = "Full path to the output HTML report")]
    [ValidateNotNullOrEmpty()]
    [string]$HtmlOutput,

    [Parameter(Mandatory = $false)]
    [string]$CompanyName = "IT Department",

    [Parameter(Mandatory = $false)]
    [switch]$SendEmail,

    [Parameter(Mandatory = $false)]
    [string]$SmtpServer,

    [Parameter(Mandatory = $false)]
    [string]$MailFrom,

    [Parameter(Mandatory = $false)]
    [string[]]$MailTo,

    [Parameter(Mandatory = $false)]
    [PSCredential]$Credential
)

#region Functions

function Write-LogMsg {
    param(
        [string]$Message,
        [ValidateSet('INFO', 'WARN', 'ERROR', 'OK')]
        [string]$Level = 'INFO'
    )
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $entry = "[$ts] [$Level] $Message"
    switch ($Level) {
        'ERROR' { Write-Host $entry -ForegroundColor Red }
        'WARN'  { Write-Host $entry -ForegroundColor Yellow }
        'OK'    { Write-Host $entry -ForegroundColor Green }
        default { Write-Host $entry -ForegroundColor Gray }
    }
}

function Get-HTMLBaseline {
    <#
    .SYNOPSIS
        Returns the HTML head, CSS styles, and opening body tags.
    #>
    return @"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IT Dashboard - $CompanyName</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f4f6f9; color: #333; padding: 20px; }
        .container { max-width: 1400px; margin: 0 auto; }
        h1 { color: #1a237e; font-size: 28px; margin-bottom: 5px; }
        h2 { color: #283593; font-size: 22px; margin: 30px 0 15px 0; border-bottom: 3px solid #3f51b5; padding-bottom: 8px; }
        h3 { color: #3949ab; font-size: 17px; margin: 20px 0 10px 0; }
        .header { background: linear-gradient(135deg, #1a237e, #3949ab); color: white; padding: 30px; border-radius: 12px; margin-bottom: 30px; box-shadow: 0 4px 15px rgba(0,0,0,0.15); }
        .header h1 { color: white; font-size: 32px; }
        .header .subtitle { font-size: 14px; opacity: 0.9; margin-top: 5px; }
        .header .report-date { font-size: 13px; opacity: 0.7; margin-top: 10px; }
        .kpi-row { display: flex; gap: 20px; margin-bottom: 30px; flex-wrap: wrap; }
        .kpi-card { flex: 1; min-width: 180px; background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); text-align: center; }
        .kpi-card .value { font-size: 32px; font-weight: bold; margin: 5px 0; }
        .kpi-card .label { font-size: 13px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
        .kpi-card.green { border-top: 4px solid #4caf50; }
        .kpi-card.blue { border-top: 4px solid #2196f3; }
        .kpi-card.orange { border-top: 4px solid #ff9800; }
        .kpi-card.red { border-top: 4px solid #f44336; }
        .kpi-card.purple { border-top: 4px solid #9c27b0; }
        .value.green { color: #2e7d32; }
        .value.orange { color: #e65100; }
        .value.red { color: #c62828; }
        table { width: 100%; border-collapse: collapse; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.08); margin-bottom: 20px; }
        th { background: #3f51b5; color: white; padding: 12px 15px; text-align: left; font-weight: 600; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; }
        td { padding: 10px 15px; border-bottom: 1px solid #e8eaf6; font-size: 14px; }
        tr:hover { background: #f5f5f5; }
        tr:last-child td { border-bottom: none; }
        .badge { display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 12px; font-weight: 600; }
        .badge-ok { background: #e8f5e9; color: #2e7d32; }
        .badge-warn { background: #fff3e0; color: #e65100; }
        .badge-critical { background: #ffebee; color: #c62828; }
        .badge-info { background: #e3f2fd; color: #1565c0; }
        .disk-bar { height: 20px; background: #e0e0e0; border-radius: 10px; overflow: hidden; min-width: 120px; }
        .disk-bar-fill { height: 100%; border-radius: 10px; }
        .disk-bar-fill.green { background: #4caf50; }
        .disk-bar-fill.orange { background: #ff9800; }
        .disk-bar-fill.red { background: #f44336; }
        .footer { text-align: center; color: #999; font-size: 12px; margin-top: 40px; padding: 20px; border-top: 1px solid #ddd; }
        a { color: #3f51b5; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .status-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 20px; margin-bottom: 20px; }
        .status-card { background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
        .status-card h4 { color: #1a237e; margin-bottom: 8px; }
        .status-card .detail { font-size: 13px; color: #555; margin: 3px 0; }
        .section { margin-bottom: 25px; }
        .empty-msg { color: #999; font-style: italic; padding: 20px; background: #fafafa; border-radius: 8px; text-align: center; }
        .collapsible { background: white; border-radius: 10px; margin-bottom: 15px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); overflow: hidden; }
        .collapsible-header { padding: 15px 20px; cursor: pointer; font-weight: 600; display: flex; justify-content: space-between; align-items: center; }
        .collapsible-header:hover { background: #f5f5f5; }
        .collapsible-content { padding: 0 20px 20px 20px; }
    </style>
</head>
<body>
    <div class="container">
"@
}

function Get-HTMLFooter {
    return @"
        <div class="footer">
            <p>Generated on $(Get-Date -Format "dddd, MMMM dd, yyyy 'at' HH:mm:ss") by PowerShell Toolkit</p>
            <p>Author: Louis Denis RAZAFIMANDIMBY | <a href="https://github.com/razafimandimby-IT/powershell-toolkit">powershell-toolkit</a></p>
        </div>
    </div>
</body>
</html>
"@
}

function Get-StatusBadge {
    param([string]$Status)
    switch ($Status) {
        "OK"         { return '<span class="badge badge-ok">OK</span>' }
        "WARNING"    { return '<span class="badge badge-warn">WARNING</span>' }
        "CRITICAL"   { return '<span class="badge badge-critical">CRITICAL</span>' }
        "Active"     { return '<span class="badge badge-ok">Active</span>' }
        default      {
            if ($Status -match "Disabled|Locked|Expired|PasswordExpired") {
                return '<span class="badge badge-warn">' + $Status + '</span>'
            }
            return '<span class="badge badge-info">' + $Status + '</span>'
        }
    }
}

function Get-DiskBarHTML {
    param([double]$UsedPercent)
    $color = if ($UsedPercent -gt 90) { "red" } elseif ($UsedPercent -gt 80) { "orange" } else { "green" }
    return '<div class="disk-bar"><div class="disk-bar-fill ' + $color + '" style="width:' + [math]::Round($UsedPercent) + '%"></div></div>'
}

#endregion

#region Main Execution

# Start transcript
$logDir = Join-Path -Path (Split-Path -Path $PSScriptRoot -Parent) -ChildPath "Logs"
if (-not (Test-Path -Path $logDir)) {
    New-Item -ItemType Directory -Path $logDir -Force | Out-Null
}
$logFile = "Invoke-ITReport_$(Get-Date -Format 'yyyy-MM-dd_HH-mm-ss').log"
$logPath = Join-Path -Path $logDir -ChildPath $logFile
Start-Transcript -Path $logPath -Force | Out-Null

Write-LogMsg -Level INFO -Message "Starting IT Report generation"
Write-LogMsg -Level INFO -Message "Company: $CompanyName"

# Validate parameters
if ($SendEmail) {
    $missingParams = @()
    if (-not $SmtpServer) { $missingParams += '-SmtpServer' }
    if (-not $MailFrom) { $missingParams += '-MailFrom' }
    if (-not $MailTo) { $missingParams += '-MailTo' }
    if ($missingParams.Count -gt 0) {
        Write-LogMsg -Level WARN -Message "Email requested but missing parameters: $($missingParams -join ', '). Email will be skipped."
        $SendEmail = $false
    }
}

if (-not $ADReportPath -and -not $InventoryPath -and -not $TargetComputers) {
    Write-LogMsg -Level ERROR -Message "No data sources specified. Provide -ADReportPath, -InventoryPath, or -TargetComputers."
    Stop-Transcript
    exit 1
}

# Initialize data containers
$adData = $null
$inventoryData = @()
$reportSections = @()

# ───── SECTION 1: Active Directory Report ─────
if ($ADReportPath) {
    Write-LogMsg -Level INFO -Message "Processing AD report: $ADReportPath"
    try {
        $adData = Import-Csv -Path $ADReportPath
        Write-LogMsg -Level OK -Message "Loaded $($adData.Count) user records from AD report"
    }
    catch {
        Write-LogMsg -Level ERROR -Message "Failed to load AD report: $($_.Exception.Message)"
    }
}

# ───── SECTION 2: System Inventory ─────
if ($InventoryPath) {
    Write-LogMsg -Level INFO -Message "Loading inventory files from: $InventoryPath"
    $inventoryFiles = Get-ChildItem -Path $InventoryPath -Filter "*.json" -File
    Write-LogMsg -Level INFO -Message "Found $($inventoryFiles.Count) inventory file(s)"

    foreach ($invFile in $inventoryFiles) {
        try {
            $invData = Get-Content -Path $invFile.FullName -Raw | ConvertFrom-Json
            $inventoryData += $invData
            Write-LogMsg -Level OK -Message "  Loaded: $($invFile.Name)"
        }
        catch {
            Write-LogMsg -Level WARN -Message "  Failed to load $($invFile.Name): $($_.Exception.Message)"
        }
    }
}

# Run inventory against target computers directly
if ($TargetComputers) {
    $scriptRoot = $PSScriptRoot
    $inventoryScript = Join-Path -Path $scriptRoot -ChildPath "Get-SystemInventory.ps1"

    if (-not (Test-Path -Path $inventoryScript)) {
        Write-LogMsg -Level WARN -Message "Get-SystemInventory.ps1 not found at: $inventoryScript"
    }
    else {
        foreach ($computer in $TargetComputers) {
            Write-LogMsg -Level INFO -Message "Running inventory on: $computer"
            $tempOutput = Join-Path -Path $env:TEMP -ChildPath "Inventory_$computer.json"

            $invParams = @{
                ComputerName = $computer
                OutputPath   = $tempOutput
                IncludeSoftware = $true
            }
            if ($Credential) { $invParams['Credential'] = $Credential }

            try {
                & $inventoryScript @invParams
                if (Test-Path -Path $tempOutput) {
                    $invData = Get-Content -Path $tempOutput -Raw | ConvertFrom-Json
                    $inventoryData += $invData
                    Write-LogMsg -Level OK -Message "  Inventory completed for: $computer"
                }
            }
            catch {
                Write-LogMsg -Level WARN -Message "  Inventory failed for $computer : $($_.Exception.Message)"
            }
        }
    }
}

# ───── BUILD HTML REPORT ─────
Write-LogMsg -Level INFO -Message "Building HTML report..."

$html = [System.Text.StringBuilder]::new()
[void]$html.Append((Get-HTMLBaseline))

# Header
[void]$html.Append(@"
<div class="header">
    <h1>$CompanyName — IT Dashboard</h1>
    <div class="subtitle">PowerShell Toolkit — Automated IT Reporting</div>
    <div class="report-date">Report generated: $(Get-Date -Format "dddd, MMMM dd, yyyy HH:mm:ss")</div>
</div>
"@)

# KPI Cards
$kpiHTML = '<div class="kpi-row">'
$totalUsers = if ($adData) { $adData.Count } else { 0 }
$totalMachines = $inventoryData.Count

# AD KPIs
if ($adData) {
    $disabledUsers = @($adData | Where-Object { $_.Enabled -eq 'False' -or $_.AccountStatus -match 'Disabled' }).Count
    $lockedUsers = @($adData | Where-Object { $_.LockedOut -eq 'True' -or $_.AccountStatus -match 'Locked' }).Count
    $inactiveUsers = @($adData | Where-Object { $_."DaysSinceLastLogon" -ne 'N/A' -and [int]$_."DaysSinceLastLogon" -gt 90 }).Count

    $kpiHTML += @"
    <div class="kpi-card blue">
        <div class="label">Total AD Users</div>
        <div class="value blue">$totalUsers</div>
    </div>
    <div class="kpi-card orange">
        <div class="label">Disabled Accounts</div>
        <div class="value orange">$disabledUsers</div>
    </div>
    <div class="kpi-card red">
        <div class="label">Locked Accounts</div>
        <div class="value red">$lockedUsers</div>
    </div>
    <div class="kpi-card orange">
        <div class="label">Inactive (90d+)</div>
        <div class="value orange">$inactiveUsers</div>
    </div>
"@
}

# Machine KPIs
if ($inventoryData.Count -gt 0) {
    $diskAlerts = 0
    $totalRAM = 0
    $osCounts = @{}

    foreach ($machine in $inventoryData) {
        if ($machine.OperatingSystem) {
            $osName = $machine.OperatingSystem.Caption
            if ($osName) {
                $osCounts[$osName] = [int]$osCounts[$osName] + 1
            }
        }
        if ($machine.Hardware) {
            $totalRAM += $machine.Hardware.TotalRAMGB
        }
        if ($machine.LogicalDisks) {
            $diskAlerts += @($machine.LogicalDisks | Where-Object { $_.Alert -ne 'OK' }).Count
        }
    }

    $kpiHTML += @"
    <div class="kpi-card purple">
        <div class="label">Total Machines</div>
        <div class="value">$totalMachines</div>
    </div>
    <div class="kpi-card blue">
        <div class="label">Total RAM</div>
        <div class="value blue">$([math]::Round($totalRAM, 0)) GB</div>
    </div>
    <div class="kpi-card $(if($diskAlerts -gt 0){'red'}else{'green'})">
        <div class="label">Disk Alerts</div>
        <div class="value $(if($diskAlerts -gt 0){'red'}else{'green'})">$diskAlerts</div>
    </div>
"@
}

$kpiHTML += '</div>'
[void]$html.Append($kpiHTML)

# ───── AD User Table ─────
if ($adData) {
    [void]$html.Append('<h2><i class="icon">&#128100;</i> Active Directory — User Report</h2>')

    # Summary of disabled/locked
    $problemAccounts = @($adData | Where-Object { $_.AccountStatus -ne 'Active' })
    if ($problemAccounts.Count -gt 0) {
        [void]$html.Append(@"
<div class="status-grid">
    <div class="status-card" style="border-left: 4px solid #ff9800;">
        <h4>Accounts Needing Attention</h4>
        <div class="detail">Total issues: $($problemAccounts.Count) / $totalUsers</div>
    </div>
</div>
"@)
    }

    [void]$html.Append('<div style="overflow-x: auto;"><table>')
    [void]$html.Append(@"
<thead><tr>
    <th>Name</th>
    <th>Username</th>
    <th>Email</th>
    <th>Department</th>
    <th>Title</th>
    <th>Status</th>
    <th>Last Logon</th>
    <th>Days Since Logon</th>
</tr></thead>
<tbody>
"@)

    # Show all users or at most 500 in the table
    $displayUsers = $adData | Sort-Object Name
    $truncated = $false
    if ($displayUsers.Count -gt 500) {
        $displayUsers = $displayUsers | Select-Object -First 500
        $truncated = $true
    }

    foreach ($user in $displayUsers) {
        $rowBg = if ($user.AccountStatus -ne 'Active') { ' style="background-color:#fff3e0;"' } else { '' }
        [void]$html.Append("<tr$rowBg>")
        [void]$html.Append("<td>$($user.Name)</td>")
        [void]$html.Append("<td>$($user.SamAccountName)</td>")
        [void]$html.Append("<td>$($user.Email)</td>")
        [void]$html.Append("<td>$($user.Department)</td>")
        [void]$html.Append("<td>$($user.Title)</td>")
        [void]$html.Append("<td>$((Get-StatusBadge -Status $user.AccountStatus))</td>")
        [void]$html.Append("<td>$($user.LastLogonDate)</td>")
        [void]$html.Append("<td>$($user.DaysSinceLastLogon)</td>")
        [void]$html.Append("</tr>")
    }

    [void]$html.Append("</tbody></table></div>")

    if ($truncated) {
        [void]$html.Append('<p style="color:#999;">Showing first 500 users. Full data is available in the source CSV.</p>')
    }
}
else {
    [void]$html.Append('<h2>Active Directory — User Report</h2>')
    [void]$html.Append('<div class="empty-msg">No AD report data loaded. Provide an AD report CSV with -ADReportPath.</div>')
}

# ───── System Inventory Tables ─────
if ($inventoryData.Count -gt 0) {
    [void]$html.Append('<h2><i class="icon">&#128187;</i> System Inventory</h2>')

    foreach ($machine in $inventoryData) {
        $computerName = $machine.ComputerName
        $machineOS = if ($machine.OperatingSystem) { $machine.OperatingSystem.Caption } else { "Unknown" }
        $machineModel = if ($machine.Hardware) { "$($machine.Hardware.Manufacturer) $($machine.Hardware.Model)" } else { "Unknown" }
        $machineRAM = if ($machine.Hardware) { "$($machine.Hardware.TotalRAMGB) GB" } else { "Unknown" }
        $machineCPU = if ($machine.CPU) { $machine.CPU } else { "Unknown" }
        $machineSerial = if ($machine.Hardware) { $machine.Hardware.SerialNumber } else { "Unknown" }

        [void]$html.Append(@"
<div class="collapsible">
    <div class="collapsible-header" onclick="this.nextElementSibling.style.display=this.nextElementSibling.style.display==='none'?'block':'none'">
        <span>$computerName</span>
        <span style="font-size:12px;color:#666;">$machineModel — $machineOS</span>
    </div>
    <div class="collapsible-content" style="display:block;">
"@)

        # System details
        [void]$html.Append(@"
        <table>
            <tr><th colspan="2">System Information</th></tr>
            <tr><td style="width:200px;font-weight:600;">Computer Name</td><td>$computerName</td></tr>
            <tr><td style="font-weight:600;">Operating System</td><td>$machineOS</td></tr>
            <tr><td style="font-weight:600;">Model</td><td>$machineModel</td></tr>
            <tr><td style="font-weight:600;">Serial Number</td><td>$machineSerial</td></tr>
            <tr><td style="font-weight:600;">CPU</td><td>$machineCPU</td></tr>
            <tr><td style="font-weight:600;">RAM</td><td>$machineRAM</td></tr>
            <tr><td style="font-weight:600;">Last Boot</td><td>$(if($machine.OperatingSystem){$machine.OperatingSystem.LastBootUpTime}else{'N/A'})</td></tr>
            <tr><td style="font-weight:600;">Uptime</td><td>$(if($machine.OperatingSystem){$machine.OperatingSystem.UptimeDays.ToString() + ' days'}else{'N/A'})</td></tr>
        </table>
"@)

        # Disks
        if ($machine.LogicalDisks) {
            [void]$html.Append('<h3>Logical Disks</h3>')
            [void]$html.Append('<div style="overflow-x: auto;"><table>')
            [void]$html.Append('<thead><tr><th>Drive</th><th>Volume</th><th>Size (GB)</th><th>Free (GB)</th><th>Used (GB)</th><th>Usage</th><th>Status</th></tr></thead><tbody>')
            foreach ($disk in $machine.LogicalDisks) {
                $usedPercent = if ($disk.UsedPercent) { $disk.UsedPercent } else { 0 }
                [void]$html.Append("<tr>")
                [void]$html.Append("<td><strong>$($disk.Drive)</strong></td>")
                [void]$html.Append("<td>$($disk.VolumeName)</td>")
                [void]$html.Append("<td>$($disk.SizeGB)</td>")
                [void]$html.Append("<td>$($disk.FreeSpaceGB)</td>")
                [void]$html.Append("<td>$($disk.UsedSpaceGB)</td>")
                [void]$html.Append("<td>$(Get-DiskBarHTML -UsedPercent $usedPercent) $([math]::Round($usedPercent, 1))%</td>")
                [void]$html.Append("<td>$(Get-StatusBadge -Status $disk.Alert)</td>")
                [void]$html.Append("</tr>")
            }
            [void]$html.Append('</tbody></table></div>')
        }

        # Network
        if ($machine.NetworkAdapters) {
            [void]$html.Append('<h3>Network Adapters</h3>')
            [void]$html.Append('<div style="overflow-x: auto;"><table>')
            [void]$html.Append('<thead><tr><th>Description</th><th>IP Address</th><th>MAC</th><th>DHCP</th><th>DNS Servers</th></tr></thead><tbody>')
            foreach ($nic in $machine.NetworkAdapters) {
                [void]$html.Append("<tr>")
                [void]$html.Append("<td>$($nic.Description)</td>")
                [void]$html.Append("<td>$($nic.IPAddress)</td>")
                [void]$html.Append("<td>$($nic.MACAddress)</td>")
                [void]$html.Append("<td>$($nic.DHCPEnabled)</td>")
                [void]$html.Append("<td>$($nic.DNSServers)</td>")
                [void]$html.Append("</tr>")
            }
            [void]$html.Append('</tbody></table></div>')
        }

        # Software (top 10)
        if ($machine.InstalledSoftware -and $machine.InstalledSoftware.Count -gt 0) {
            $swCount = $machine.InstalledSoftware.Count
            $topSW = $machine.InstalledSoftware | Sort-Object Name | Select-Object -First 20
            [void]$html.Append("<h3>Installed Software ($swCount applications)</h3>")
            [void]$html.Append('<div style="overflow-x: auto;"><table>')
            [void]$html.Append('<thead><tr><th>Name</th><th>Publisher</th><th>Version</th></tr></thead><tbody>')
            foreach ($sw in $topSW) {
                [void]$html.Append("<tr><td>$($sw.Name)</td><td>$($sw.Publisher)</td><td>$($sw.Version)</td></tr>")
            }
            if ($swCount -gt 20) {
                [void]$html.Append("<tr><td colspan='3' style='color:#999;font-style:italic;'>... and $($swCount - 20) more applications</td></tr>")
            }
            [void]$html.Append('</tbody></table></div>')
        }

        [void]$html.Append('</div></div>')
    }
}
else {
    [void]$html.Append('<h2>System Inventory</h2>')
    [void]$html.Append('<div class="empty-msg">No inventory data available. Provide inventory files with -InventoryPath or target computers with -TargetComputers.</div>')
}

# Footer
[void]$html.Append((Get-HTMLFooter))

# Write HTML file
try {
    $outputDir = Split-Path -Path $HtmlOutput -Parent
    if ($outputDir -and -not (Test-Path -Path $outputDir)) {
        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
        Write-LogMsg -Level INFO -Message "Created output directory: $outputDir"
    }

    $html.ToString() | Out-File -FilePath $HtmlOutput -Encoding utf8
    Write-LogMsg -Level OK -Message "HTML report generated: $HtmlOutput"
    Write-LogMsg -Level INFO -Message "Report size: $([math]::Round((Get-Item $HtmlOutput).Length / 1KB, 2)) KB"
}
catch {
    Write-LogMsg -Level ERROR -Message "Failed to write HTML report: $($_.Exception.Message)"
    Stop-Transcript
    exit 1
}

# ───── Send Email (optional) ─────
if ($SendEmail) {
    Write-LogMsg -Level INFO -Message "Sending email report to: $($MailTo -join ', ')"
    try {
        $mailParams = @{
            From         = $MailFrom
            To           = $MailTo
            Subject      = "IT Dashboard — $CompanyName ($(Get-Date -Format 'yyyy-MM-dd'))"
            Body         = "Please find attached the IT dashboard report generated on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss').`n`nThis report was generated by the PowerShell Toolkit.`n`n-- IT Department"
            SmtpServer   = $SmtpServer
            Attachments  = $HtmlOutput
        }

        Send-MailMessage @mailParams
        Write-LogMsg -Level OK -Message "Email sent successfully"
    }
    catch {
        Write-LogMsg -Level ERROR -Message "Failed to send email: $($_.Exception.Message)"
    }
}

# Summary
Write-Host ""
Write-Host "========== REPORT GENERATION SUMMARY ==========" -ForegroundColor Cyan
if ($adData) {
    Write-Host "  AD Users                    : $($adData.Count)" -ForegroundColor White
    Write-Host "  Problem accounts            : $($problemAccounts.Count)" -ForegroundColor $(if($problemAccounts.Count -gt 0){'Yellow'}else{'Green'})
}
Write-Host "  Machines inventoried        : $($inventoryData.Count)" -ForegroundColor White
Write-Host "  HTML report                 : $HtmlOutput" -ForegroundColor White
Write-Host "  Log file                    : $logPath" -ForegroundColor White
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host ""

Stop-Transcript
Write-LogMsg -Level OK -Message "Script completed successfully"

#endregion
